config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "cocktails#index"

  resources :cocktails, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :doses, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :cocktail, :ingredient, scope: [:cocktail_id, :ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy]

  def index
    @cocktail = Cocktail.new
    if params[:querry].present?
      name = params[:querry]
      @cocktails = Cocktail.where("name LIKE ?", "%#{name[:search]}%")
    else
      @cocktails = Cocktail.all
    end
  end

  def show
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  before_action :set_dose, only: [:destroy]

  def new
    @dose = Dose.new
  end

  def create
    @dose = @cocktail.doses.build(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show', locals: { dose: @dose.id }
    end
  end

  def destroy
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = @cocktail.reviews.build(review_params)
    if @review.save 
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end 
  end 


  private 

  def review_params
    params.require(:review).permit(:content, :rating)
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "New Cocktail", new_cocktail_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "New Cocktail", new_cocktail_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/cocktails/index.html.erb
<h1 class="header text-center"></h1>
<div class="search d-flex justify-content-center">
  <%= simple_form_for :querry, url: root_path, method: :get, html: { class: 'form-inline' } do |f| %>
    <%= f.input :search, label: false %>
    <div class="d-flex align-items-center">
      <%= f.button :submit, class: "btn btn-primary mx-2" %>
      <%= link_to "delete filters", root_path, class: "btn btn-secondary"%>
    </div>
  <% end  %>
</div>

<div class="cards w-100">
  <div class="row justify-content-center">
    <% @cocktails.each do |cocktail| %>
      <div class="card-trip col-3 my-3 mx-2" data-aos="zoom-out">
        <%= cl_image_tag cocktail.photo.key, height: 300, width: 300, class: "mt-3" %>
        <div class="card-trip-infos">
          <div  class="mb-2">
            <h2><%= cocktail.name %></h2>
          </div>
          <div>
            <%= link_to "Voir", cocktail_path(cocktail), class:"btn btn-primary" %>
            <%= link_to "Delete", cocktail_path(cocktail), method: :delete, class:"btn btn-danger", data: { confirm: "Are you sure ? "} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Ajouter un cocktail</h1>
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end  %>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),  url(<%= cl_image_path @cocktail.photo.key%>);background-size: cover;
  background-repeat: no-repeat; height: 400px">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <%= link_to "Back", root_path, class:"btn btn-secondary" %>
  </div>
</div>

<h2>Ingredients </h2>
<ul>
  <% @cocktail.doses.each do |dose| %>
    <li>
      <%= dose.ingredient.name %> <%= dose.description %> <%= link_to "delete", dose_path(dose), method: :delete, class:"btn btn-danger", data: { confirm: "Are you sure ?"} %>
    </li>
    
  <% end %>
</ul>

<h2>Reviews</h2>
<% if @cocktail.reviews.count == 0 %>
<p>Il n'y a pas de review pour ce cocktail</p>
<% else %>
  <% @cocktail.reviews.each do |review| %>
    <p class="border-bottom"><b><%= "*" * review.rating %></b><%= review.content %></p>
    <br/>
  <% end %>
<% end %>


<div class="d-flex justify-content-around">
  <div>
    <h2>Ajouter une dose</h2>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.input :description, collection: ["2cl", "3cl", "4cl", "5cl"] %>
      <%= f.association :ingredient, input_html: { class: 'select2' }, prompt: "Choose a Ingredient" %>
      <%= f.button :submit,class: "btn btn-primary" %>
    <% end %>
  </div>
  <div>
    <h2>Ajouter une review</h2>
    <%= simple_form_for [@cocktail, @review], remote: true do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.button :submit,class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail345</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
  </head>

  <body>
    <%= render "navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  </body>
</html>